### ISSUE TITLE
Crashed when loading in PO3

### ISSUE THREAD

**Issue by Dm5354** [DeadlyMC/ForgedCarpet112#10]
While loading in the forgeloader crashes in the initialitation phase!

https://pastebin.pl/view/8478338b

**Comment by DeadlyMC** [comment]
Yeah it was related to `newLight` which is gonna be removed in the next release...u could build a jar yourself from github..it should hv it fixed

**Comment by DeadlyMC** [comment]
or wait for the new release which i cant really give an eta for....

**Comment by Dm5354** [comment]
Alright thanks, I will give it a shot, if you have it updated can you mail me please?

**Comment by DeadlyMC** [comment]
r u on discord? I could send u a jar to test quickly there

**Comment by Dm5354** [comment]
Yes I am on discord!

GhostKilller (dm5354)#2340

**Comment by Dm5354** [comment]
I've sent it in email!

**Comment by DeadlyMC** [comment]
How do u know my email tho? I didnt receive any mails too

**Comment by Dm5354** [comment]
NW, I got it sorted! I will explain it on discord!

Yes I am on discord!

GhostKilller (dm5354)#2340

**Comment by DeadlyMC** [comment]
I just sent u a friend request, DeadlyMC#9052

**Comment by DeadlyMC** [comment]
Closing this issue as per discussion on discord, make sure u update to the new release whenever its out.
