### ISSUE TITLE
no config file

### ISSUE THREAD

**Issue by AlienXtream** [DeadlyMC/ForgedCarpet112#11]
cant find the config file and settings not persisting on reloading save/game

**Comment by DeadlyMC** [comment]
Which version of the mod are you running? Can you provide more context

**Comment by AlienXtream** [comment]
version 1.3.1 when i was trying it but i DID update to 1.3.2 (never tested that version though, just disabled till i could resolve this)

**Comment by DeadlyMC** [comment]
Do you `/carpet setDefault` ?

**Comment by DeadlyMC** [comment]
The config file is basically the `carpet.conf` file in your worlds folder

**Comment by AlienXtream** [comment]
ah. save, not config

**Comment by AlienXtream** [comment]
might want to mention that on the mod page so people know where it is to manual edit.

**Comment by DeadlyMC** [comment]
Im sorry, i still dont understand what issue you are facing here

**Comment by DeadlyMC** [comment]
> 
> 
> might want to mention that on the mod page so people know where it is to manual edit.

True, will add that. But why will u manually edit the file?

**Comment by AlienXtream** [comment]
it wasn't saving any of the settings i changed. they reverted when i went to the main menu (i did click the thing to save them)

**Comment by DeadlyMC** [comment]
Hmmm, i did test the mod before releasing..it was saving..not sure why it isnt for you. Are you running a dedicated server or singleplayer?

**Comment by DeadlyMC** [comment]
Can you maybe provide your `latest.log` file

**Comment by DeadlyMC** [comment]
> 
> 
> it wasn't saving any of the settings i changed. they reverted when i went to the main menu (i did click the thing to save them)

![image](https://user-images.githubusercontent.com/43000902/106352910-b3122400-630c-11eb-8418-18929de5c941.png)
Do you click on `change permanently` after you set a carpet rule to true?

**Comment by AlienXtream** [comment]
the other "issue" was that i assumed there would be a config file in the actual config folder (like most mods). why one would want to manually edit is:
-if the settings dont save (like in this case)
- advanced users wanting to mess with the file
- bugs/startup crashes due to one or more of the features and having a way of disabling them out of the game (just an example)

im not actually in MC atm (and it aint exactly a quick start up time) but i will test things more and provide feedback later. it very well could just be user error due to lack of understanding or it could be an actual problem with the mod. 
unrelated but will ask quickly while im here. movable TEs. planned or not? (its the main reason i wanted the mod :P)

**Comment by AlienXtream** [comment]
yes, i did click that thing and hit enter on the command

**Comment by DeadlyMC** [comment]
> the other "issue" was that i assumed there would be a config file in the actual config folder

Does forge have a config folder for servers? Also i hvnt done this, cuz this is more of a port of carpetmod and it stores it in the world folder itself :p

**Comment by AlienXtream** [comment]
oh right. forgot. SP.

 i understand that its a port. thinking about it it makes sense the config would be in the save game folder given that each setting is per world. could consider adding a forge config file for "default settings" but totally not needed.

**Comment by DeadlyMC** [comment]
Also can you set default and then go to your world folder and check if a carpet.conf exists, do this withut going to the main menu.

**Comment by DeadlyMC** [comment]
Cause i am literally testing it right now and it works like a charm

**Comment by DeadlyMC** [comment]
> unrelated but will ask quickly while im here. movable TEs. planned or not? (its the main reason i wanted the mod :P)

I havent ported movable-te's cause well it results in so many conflicts with other mods, i will most probably make that a different mod after asking permission from the original writer of that code. So you might wonna follow me on github or curseforge ;)

**Comment by AlienXtream** [comment]
![image](https://user-images.githubusercontent.com/12606809/106353047-d607fc80-633b-11eb-9ee6-04e4d35afe12.png)
its there. seems to have been user error. tbf this was more a question post that a bug report. if i were reporting a bug i would be far more thorough with my details.

**Comment by DeadlyMC** [comment]
Open it and check if your carpet rule is saved in it

**Comment by AlienXtream** [comment]
> king permission from the original writer of that code. So you might wonna follow me on github or curseforge ;)

understandable. there are other mods that do stuff like that with TE's. could perhaps limit it to vanilla TEs if thats possible, idk how code works in this case.

**Comment by AlienXtream** [comment]
and yeh, there was something in the configs. the others did not save but the respawn shulkers was there

**Comment by DeadlyMC** [comment]
The mod im talking about is quark, it has movable te's too and it would conflict..wonna avoid that :p so yea most prolly coming to a different mod

**Comment by AlienXtream** [comment]
quark makes vanilla TEs movable?!

**Comment by DeadlyMC** [comment]
> 
> 
> and yeh, there was something in the configs. the others did not save but the respawn shulkers was there

Not sure why others didnt save, if you could provide a way to reproduce the issue then i could help

**Comment by DeadlyMC** [comment]
> 
> 
> quark makes vanilla TEs movable?!

Yes the 1.12.2 version atleast afaik

**Comment by AlienXtream** [comment]
as i said, cant test it atm (well. i can but im playing something else and CBA waiting 20 mins for MC to load. yes, 20 mins with 400+ mods. if its stable for me then its stable :P). most reliable way would probably be being me... :/ seriously, i jsut have a knack for finding these sorts of bugs (assuming it is a bug)

**Comment by DeadlyMC** [comment]
oh you are running a modpack, maybe something else breaks carpet..not sure what r the chances it breaks the saving part, but sending your latest.log file (after you have ran ur modpack and it didnt save the config file) might help.

**Comment by DeadlyMC** [comment]
But ig have this issue open for now, test it when u can lemme know

**Comment by AlienXtream** [comment]
eh. ima start it up. cya in 20 mins or so :P

**Comment by AlienXtream** [comment]
alright. its almost loaded. what am i testing again?

**Comment by AlienXtream** [comment]
....sigh.... i forgot to reenable forged-carpet... -_-

**Comment by AlienXtream** [comment]
you see now how easily it could be user error??? XD

**Comment by DeadlyMC** [comment]
Lmao

**Comment by DeadlyMC** [comment]
> 
> 
> alright. its almost loaded. what am i testing again?

Just open the world and set different rules to setdefault true (or false ig) and then without closing the world go and check the config file and then close the world and then again check the config file...and send me your `latest.log` file too maybe

**Comment by AlienXtream** [comment]
yeh ok. it works. i guess it just needed some convincing :P

**Comment by DeadlyMC** [comment]
Can we close this issue then? :p
