### ISSUE TITLE
FIllUpdates and FillLimit don't work properly

### ISSUE THREAD

**Issue by Ghoulboy78** [DeadlyMC/ForgedCarpet112#5]
I set the fill limit to 1 million, but when I tried filling in the area with air, it gave me the error that the area exceeded the limit of 32768 blocks. Then when I actually split it up into little slices and set the fillUpdates to false, there was still lava flowing when I tried making the perimeter.

**Comment by DeadlyMC** [comment]
Hmm, where u running any other mods?

**Comment by Ghoulboy78** [comment]
I was, and when I tried again they both worked, but there is a new weird bug in that it wouldn't show the number of blocks that had been removed or selected for removing, it only shows the limit.
![2019-09-08_15 49 18](https://user-images.githubusercontent.com/53367549/64489194-5d893300-d250-11e9-97f0-86a526ff9e25.png)

**Comment by DeadlyMC** [comment]
What are the other mods u r running? Also could u provide a log of the game where this bug occurs

**Comment by Ghoulboy78** [comment]
that time I was running no other mods

**Comment by DeadlyMC** [comment]
Should be fixed in v1.2.1
