### ISSUE TITLE
Server crash in SevTech Ages

### ISSUE THREAD

**Issue by MrW00dy** [DeadlyMC/ForgedCarpet112#6]
Hi, I run a SevTech Ages (v3.1.7) server for me and my buddy, when I try to start the server with the ForgedCarpet-1.12.2-1.2.1.jar file in the mod folder it crashes.
So I cleared the console and tried to start the server again and dumped everything in this [Pastebin](https://pastebin.com/E4Ls7u1E), I would really appreciate it you took a look at it to see what I'm missing here. The only mod I added to the pack is ChickenChunks but I don't think that's the problem.

Thanks in advance.

**Comment by DeadlyMC** [comment]
Did you try running a fresh instance without ForgedCarpet, but just SavTech ages?

**Comment by DeadlyMC** [comment]
Also there doesnt really seem to be anything in the pastebin u sent....is there a crash-report somewhere that i can look at?
I hvnt run modpacks before...but the first thing i notice in the files section is that there are additional files for servers, do u hv those on when running the server? @MrW00dy

**Comment by MrW00dy** [comment]
I don't have any plugins just the modpack's mods and I tried it again from a fresh install of the server but it's always the same it doesn't even initialize, it just stops when I try to start it and it doesn't produce a crash report. Maybe it's just incompatible with this pack. Thanks anyway.

**Comment by DeadlyMC** [comment]
Are you using the twitch launcher to run the modpack? and r u running a server or just singleplayer?

**Comment by MrW00dy** [comment]
I'm running it from ggservers.com

**Comment by DeadlyMC** [comment]
I just ran forged-carpet (with all the fixes that will be there in the next release) with sevtech ages on my system and it didnt crash. If you would want to test yourself u would need to provide me ur discord if so i can send u a mod jar to test with

**Comment by DeadlyMC** [comment]
This was probably related to 79cd6bc357eca9e40c7da357a78d05d18b89a3a0

**Comment by DeadlyMC** [comment]
1.3.0 is on github now! You should be able to run SevTechAges with forged-carpet now. Thanks for reporting!
