### ISSUE TITLE
Crash when creating or joining existing world while using ForgedCarpet on FTB Direwolf20 1.12.2 Modpack

### ISSUE THREAD

**Issue by Tsunoii** [DeadlyMC/ForgedCarpet112#7]
I've added ForgedCarpet to my mods folder, I am using the FTB Direwolf20 1.12.2 Modpack from the Curseforge Overwolf Launcher, I've added Optifine, VeinMiner, TorchMaster, and Tinker's Construct Tool Leveling mods to the modpack (in case any of these mods are causing some sort of conflict with the ForgedCarpet mod)
Without ForgedCarpet, the game works fine and I can join or create any single-player world, or join any server, but with the mod installed, the game crashes to the launcher whenever I create a new world or load into a world I made earlier, The launcher gives me this info:

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchFieldError: lightingEngine
Exit Code: -1

And this is the full crash report:

https://pastebin.com/vJeDP0D7

**Comment by Khaelum** [comment]
Adding to this, I have tracked it down to the problem being incompatibility with phosphor.
**Correction: Phosphor is one of the compatibility issues, there seems to be more.

**Comment by DeadlyMC** [comment]
Issue with phosphor should be fixed in the next release, i decided to remove `newLight` as that already exists in MUP and i believe phosphor too is a light engine optimization...so there's no need of having duplicates.

**Comment by DeadlyMC** [comment]
Closed with 7572da00a8dcbb5915d7827ca988828c52c56955
