### ISSUE TITLE
Crash when ticking world.

### ISSUE THREAD

**Issue by Khaelum** [DeadlyMC/ForgedCarpet112#8]
ForgedCarpet causes a crash whenever one of these mods are present:

- appliedenergistics2-rv6-stable-7
- Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89
- extrautils2-1.12-1.9.9
- lostcities-1.12-2.0.21
- Simple-Void-World-1.12-1.2.0.9-universal
- twilightforest-1.12.2-3.9.984-universal
- woot-1.12.2-1.4.11

Logs are as follows
[crash_ae2.txt](https://github.com/DeadlyMC/ForgedCarpet/files/5667373/crash_ae2.txt)
[crash_twilight.txt](https://github.com/DeadlyMC/ForgedCarpet/files/5667379/crash_twilight.txt)
[crash_extrautils2.txt](https://github.com/DeadlyMC/ForgedCarpet/files/5667392/crash_extrautils2.txt)
[crash_lostcities.txt](https://github.com/DeadlyMC/ForgedCarpet/files/5667402/crash_lostcities.txt)

Didnt get logs for all of them, but they all crash with the same log output.

**Comment by DeadlyMC** [comment]
Would you be able to make a build yourself and test it out, cuz a1be528b68bc19abfce2fdd589701185c8e5b878 shouldve fixed it...so it shld be good in the upcoming release. r u on discord?, cuz then i can provide you a jar to test with

**Comment by Khaelum** [comment]
Built and tested, seems fixed!
