### ISSUE TITLE
Crash when mobcap is set to be shown while inside a custom dimension.

### ISSUE THREAD

**Issue by Khaelum** [DeadlyMC/ForgedCarpet112#9]
First of all, I am assuming this crash occurs on any custom dimension, as I have only tested it for Aroma1997's Dimensional World.
[crash-2020-12-12_20.48.17-server.txt](https://github.com/DeadlyMC/ForgedCarpet/files/5683958/crash-2020-12-12_20.48.17-server.txt)

ForgedCarpet version was built up to commit cf7be7e.

**Comment by Ghoulboy78** [comment]
I think the fix is just to check for the dimension, and then incase it's not one of three vanilla dimensions, just to say whooops, invalid dimension.

**Comment by DeadlyMC** [comment]
> 
> 
> I think the fix is just to check for the dimension, and then incase it's not one of three vanilla dimensions, just to say whooops, invalid dimension.

This would be more of a hackfix ig, the changes i made should allow users to view mobcaps in custom dimensions too
